USE mondelys_db;
SET NAMES utf8mb4;

-- Optionnel si vous voulez recharger le menu statique depuis zero :
-- DELETE FROM menu;

INSERT INTO menu (
  name,
  cuisine,
  location,
  price,
  pieces,
  description,
  badge_labels,
  image_url,
  display_order,
  active,
  created_at,
  updated_at
) VALUES
(
  'Japanese GYOZA (Dumplings)',
  'JAPON',
  'Tokyo, Japon',
  '56 TND',
  '8 pieces',
  '6 ravioles grillees-vapeur, farce porc iberique, truffe noire et gingembre confit, sauce ponzu maison. -NON HALAL-',
  'Chef''s Choice',
  'images/GYOZA.jpg',
  0,
  1,
  NOW(6),
  NOW(6)
),
(
  'Sushi Cru',
  'JAPON',
  'Japon',
  '96 TND',
  '16 pieces',
  'Delicat sushi au saumon cru, accompagne d''avocat fondant et de graines de sesame, sur un riz vinaigre parfaitement assaisonne. Accompagne d''une sauce soja subtilement salee et sucree. Option : par pieces.',
  'Releve|Signature',
  'images/SUSHI1.jpg',
  1,
  1,
  NOW(6),
  NOW(6)
),
(
  'Sushi Cuit',
  'JAPON',
  'Japon',
  '55 TND',
  NULL,
  'Un sushi crunchy irresistible : saumon cuit tendre a coeur, texture croustillante a l''exterieur, avocat cremeux et sauce soja douce et equilibree. Option : par pieces.',
  'Signature',
  'images/SUSHI2.jpg',
  2,
  1,
  NOW(6),
  NOW(6)
),
(
  'Chicken Ramen',
  'JAPON',
  'Fukuoka, Japon',
  '45 TND',
  NULL,
  'Bouillon parfume et legerement piquant, poulet delicatement marine et nouilles soyeuses, sublimes par des epices soigneusement selectionnees.',
  'Signature',
  'images/Fiery_Chicken.jpg',
  3,
  1,
  NOW(6),
  NOW(6)
),
(
  'Katsu curry',
  'JAPON',
  'Japon',
  '35 TND',
  NULL,
  'Poulet pane croustillant, nappe d''une sauce curry relevee et epicee, servi avec du riz moelleux pour une explosion de saveurs.',
  'Nouveau',
  'images/Katsu.jpg',
  4,
  1,
  NOW(6),
  NOW(6)
),
(
  'Takoyaki',
  'JAPON',
  'Japon',
  '40 TND',
  '6 pieces',
  'Boulettes de pate moelleuse garnies de morceaux de poulpe, cuites a la perfection et nappees d''une sauce takoyaki savoureuse, parsemees de flocons de bonite et d''algues.',
  'Poulpe',
  'images/Takoyaki.jpg',
  5,
  1,
  NOW(6),
  NOW(6)
),
(
  'Cheesy & Beef Enchiladas',
  'MEXIQUE',
  'Mexique',
  '40 TND',
  NULL,
  'Tortillas garnies de boeuf tendre et de fromage fondant, baignees dans une sauce relevee pour un melange de saveurs gourmandes et authentiques.',
  'Halal|Nouveau',
  'images/Cheesy_Beef.jpg',
  0,
  1,
  NOW(6),
  NOW(6)
),
(
  'Mexicano Tacos',
  'MEXIQUE',
  'Mexico City, Mexique',
  '50 TND',
  NULL,
  'Un plateau de tortillas aux multiples garnitures, alliant textures et saveurs pour un plaisir partage a chaque bouchee.',
  'Chef''s Choice',
  'images/Tortillas.jpg',
  1,
  1,
  NOW(6),
  NOW(6)
),
(
  'Guacamole',
  'MEXIQUE',
  'Mexique',
  '26 TND',
  NULL,
  'Puree d''avocat cremeuse avec tomates, oignons, coriandre et citron vert.',
  'Signature',
  'images/Guacamole.jpg',
  2,
  1,
  NOW(6),
  NOW(6)
),
(
  'Mole Poblano',
  'MEXIQUE',
  'Originaire de Puebla, Mexique',
  '52 TND',
  NULL,
  'Poulet nappe d''une sauce riche au chocolat, piments et epices mexicaines.',
  'Halal|Des saveurs sucrees et epicees',
  'images/Poblano.jpg',
  3,
  1,
  NOW(6),
  NOW(6)
),
(
  'Spaghetti Carbonara Originale',
  'ITALIE',
  'Rome, Italie',
  '50 TND',
  NULL,
  'L''authentique Carbonara italienne : spaghetti parfaitement cuits, sauce onctueuse aux oeufs et Pecorino, morceaux de pancetta doree et touche de poivre noir.',
  'Authentique',
  'images/carbonara.jpg',
  0,
  1,
  NOW(6),
  NOW(6)
),
(
  'Ravioli del chef',
  'ITALIE',
  'Italie',
  '40 TND',
  NULL,
  'Pates fraiches farcies genereusement, servies avec une sauce delicate a base de tomates, beurre ou creme, et relevees de parmesan fraichement rape.',
  'Epicee|Chef''s Choice',
  'images/Raviolis.jpg',
  1,
  1,
  NOW(6),
  NOW(6)
),
(
  'Ravioli Bianca',
  'ITALIE',
  'Italie',
  '40 TND',
  NULL,
  'Ravioli fondants, genereusement garnis et enveloppes d''une sauce blanche cremeuse, pour une explosion de saveurs italiennes a chaque bouchee.',
  'Chef''s Choice',
  'images/ravioli.jpg',
  2,
  1,
  NOW(6),
  NOW(6)
),
(
  'Pizza Burrata',
  'ITALIE',
  'Naples, Italie',
  '35 TND',
  NULL,
  'Pate Napolitaine, garnie de tomates fraiches, roquette croquante et burrata cremeuse fondante a coeur, pour une experience italienne raffinee.',
  'Vegetarien|Signature',
  'images/burrata1.jpg',
  3,
  1,
  NOW(6),
  NOW(6)
),
(
  'Pizza 4 fromages',
  'ITALIE',
  'Napoli',
  'Moyenne 20 TND|Large 30 TND',
  NULL,
  'Pizza genereuse nappée de quatre fromages fondants - mozzarella, Gorgonzola, Parmesan et Fontina - pour une explosion cremeuse de saveurs italiennes.',
  'Signature',
  'images/pizza4.jpg',
  4,
  1,
  NOW(6),
  NOW(6)
),
(
  'Pizza champignons & Tomates',
  'ITALIE',
  'Napoli',
  'Moyenne 22 TND|Large 32 TND',
  NULL,
  'Une harmonie de champignons frais, tomates mures et fromage fondant, pour un gout a la fois leger et savoureux.',
  'Signature',
  'images/champ.jpg',
  5,
  1,
  NOW(6),
  NOW(6)
),
(
  'Rigatoni',
  'ITALIE',
  'Milan, Italie',
  '42 TND',
  NULL,
  'Rigatoni al dente, enrobes d''une sauce a la viande mijotee lentement aux tomates et herbes italiennes, pour un gout authentique et reconfortant.',
  'Sans Gluten',
  'images/Rigatoni.jpg',
  6,
  1,
  NOW(6),
  NOW(6)
),
(
  'BRUSCHETTA',
  'ITALIE',
  'Venise, Italie',
  '15 TND',
  '2 pieces',
  'Bruschetta croquante garnie de tomates fraiches, basilic et fromage fondant, assaisonnee d''un filet d''huile d''olive extra vierge.',
  'Vegetarien',
  'images/BURRATAA.jpg',
  7,
  1,
  NOW(6),
  NOW(6)
),
(
  'Creamy Dreamy Chicken & Mushroom Tagliatelle Delight',
  'ITALIE',
  'Bologne, Italie',
  '52 TND',
  NULL,
  'Tagliatelle a la sauce blanche, enrobees d''une sauce onctueuse et subtilement assaisonnee, pour un plat reconfortant et plein de gout.',
  NULL,
  'images/tagliatelle.jpg',
  8,
  1,
  NOW(6),
  NOW(6)
),
(
  'Hummus',
  'ORIENTALE',
  'Lebanon, Syrie',
  '16 TND',
  NULL,
  'Une puree onctueuse de pois chiches, delicatement assaisonnee de tahini, citron et huile d''olive, pour un gout doux, cremeux et authentiquement oriental.',
  'Epicee|Chef''s Choice',
  'images/houmous.jpg',
  0,
  1,
  NOW(6),
  NOW(6)
),
(
  'Kebbe',
  'ORIENTALE',
  'Lebanon, Syrie',
  '20 TND',
  '4 pieces',
  'Boulettes dorees et parfumees, alliant viande epicee et boulgour, pour une explosion de saveurs orientales a chaque bouchee.',
  'Chef''s Choice',
  'images/kibbah.jpg',
  1,
  1,
  NOW(6),
  NOW(6)
),
(
  'Yabraq',
  'ORIENTALE',
  'Syrie, Lebanon',
  '18 TND',
  NULL,
  'Des roules savoureux de feuilles de vigne garnies de riz et d''epices, pour un plat aromatique et reconfortant.',
  'Authentique',
  'images/dolmas.jpg',
  2,
  1,
  NOW(6),
  NOW(6)
),
(
  'Tabbouleh',
  'ORIENTALE',
  'Syrie, Lebanon',
  '16 TND',
  NULL,
  'Une salade fraiche et legere a base de persil, boulgour, tomates et citron, pleine de saveurs et de fraicheur orientale.',
  'Vegetarien|Signature',
  'images/tabbouleh.jpg',
  3,
  1,
  NOW(6),
  NOW(6)
),
(
  'Maqlouba',
  'ORIENTALE',
  'Palestine, Jordanie',
  '35 TND',
  NULL,
  'Delicieux melange de riz, legumes et viande, prepare avec soin et presente renverse, pour un festival de saveurs authentiques.',
  'Signature',
  'images/maklouba.jpg',
  4,
  1,
  NOW(6),
  NOW(6)
),
(
  'Mochi Ice Cream Collection',
  'DESSERTS',
  'Kyoto, Japon',
  '32 TND',
  NULL,
  'Selection de 6 mochis artisanaux : matcha Uji, yuzu, sakura, sesame noir, mangue Alphonso et litchi-rose.',
  'Sucree',
  'images/Mochi.jpg',
  0,
  1,
  NOW(6),
  NOW(6)
),
(
  'Tiramisu Nutella',
  'DESSERTS',
  'Italie',
  '18 TND',
  NULL,
  'Dessert italien emblématique a base de biscuits imbibes de cafe, mascarpone cremeux et cacao saupoudre, pour un equilibre parfait entre douceur et intensite.',
  'Chef''s Choice',
  'images/tiramisu.jpg',
  1,
  1,
  NOW(6),
  NOW(6)
),
(
  'Churros Dulce de Leche',
  'DESSERTS',
  'Mexico City',
  '40 TND',
  NULL,
  'Batonnets dores et croustillants, sucres a souhait et servis avec une sauce chocolat onctueuse, pour un vrai regal gourmand.',
  NULL,
  'images/Chocolate_Heaven.jpg',
  2,
  1,
  NOW(6),
  NOW(6)
),
(
  'Küneffah',
  'DESSERTS',
  'Syrie',
  'Moyenne 15 TND|Large 22 TND',
  NULL,
  'Douceur du Moyen-Orient : fromage fondant enveloppe de fils de pate croustillants, nappe d''un sirop delicatement parfume.',
  NULL,
  'images/kunefe.jpg',
  3,
  1,
  NOW(6),
  NOW(6)
),
(
  'The vert a la menthe',
  'DESSERTS',
  NULL,
  '10 TND',
  NULL,
  'Supplements : amandes, pignons.',
  NULL,
  'images/Tunisian_tea.jpg',
  4,
  1,
  NOW(6),
  NOW(6)
),
(
  'Cafe Arabique',
  'DESSERTS',
  NULL,
  '8 TND',
  NULL,
  'Cafe traditionnel fort et aromatique, prepare lentement pour reveler ses saveurs intenses et sa texture veloutee.',
  NULL,
  'images/cafe.jpg',
  5,
  1,
  NOW(6),
  NOW(6)
),
(
  'Menu Degustation 7 Plats',
  'DESSERTS',
  '3 Continents',
  '480 TND',
  NULL,
  'Tour du monde en 7 escales - a commander 48h a l''avance.',
  'Experience',
  'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=200&q=80',
  6,
  1,
  NOW(6),
  NOW(6)
);
